---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - 2.5.1
before_install: gem install bundler -v 1.16.4
gemfile:
  - Gemfile
  - gemfiles/activemodel-4.2.gemfile
  - gemfiles/activemodel-5.1.gemfile
  - gemfiles/activemodel-5.2.gemfile
  - gemfiles/activemodel-master.gemfile
matrix:
  allow_failures:
  - gemfile: gemfiles/activemodel-master.gemfile
fast_finish: true